version: '2'
 
services:

  proxy:
    build:
      context:  ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    links:
      - app
      
  app:
    build:
      context:  ./app
      dockerfile: Dockerfile
    expose:
      - "5000"
